### ISSUE TITLE
Dapper, a Large-Scale Distributed Systems Tracing Infrastructure

### ISSUE THREAD

**Issue by cookk** [12orange/labs#5]
https://static.googleusercontent.com/media/research.google.com/ko//pubs/archive/36356.pdf

**Comment by ChaehyeonLee** [comment]
# Dapper, 대규모 분산 시스템 추적 인프라
Benjamin H. Sigelman, Luiz Andre Barroso, Mike Burrows, Pat Stephenson, ´
Manoj Plakal, Donald Beaver, Saul Jaspan, Chandan Shanbhag
## 개요(Abstract)
  현대의 인터넷 서비스는 흔히 복잡하고, 큰 규모의 분산 시스템으로 구현된다. 이런 어플리케이션들은 소프트웨어 모듈들의 집합으로 구성되는데, 이는 서로 다른 팀에서 개발될 수 있고, 아마 다른 프로그래밍 언어를 사용해서, 그리고 다수의 물리적 시설들을 가로지르는 수천개의 기계들에 걸쳐있을 수 있다. 이러한 환경에서, 시스템의 동작에 대한 이해와 성능 이슈에 대한 판단에 도움을 주는 도구(tool)들은 매우 가치있다.
  우리는 여기서 Google의 생산 분산 시스템 추적 인프라인 Dapper의 디자인에 대해 소개하고, 어떻게 우리의 디자인 목표인 적은 오버헤드, 어플리케이션 레벨의 투명성, 그리고 매우 큰 규모의 시스템에서의 편재형 배치(ubiquitous deployment)를 충족하였는지에 대해 설명한다. Dapper는 다른 추적 시스템들, 특히 Magpie [3] 과 X-Trace [12]와 개념적인 유사도를 공유하지만, 특정한 디자인 선택들(design choices)이 우리의 환경에서 Dapper의 성공의 핵심 열쇠가 되었다. 그 선택들은, 예를 들어, 샘플링을 사용하고 Instrumentation을약간 적은 수의 공동의 라이브러리들로 제한하는 것들이다.
  이 논문의 주된 목표는 시스템의 building, deploying 그리고 2년이 넘는 시간 동안의 using대한 우리의 경험을 알리는 것이고, 이는 Dapper의 가장 중요한 성공의 방법이 개발자들과 operations team들에게 유용해졌기 때문이다. Dapper는 독립적인(self-contained) 추적 도구로 시작했지만, 몇몇은 Dapper의 디자이너들도 예측하지 못했던, 다른 많은 도구(tool)들의 창조를 가능하게 하는 모니터링 플랫폼으로 발전했다. 우리는 Dapper를 이용해 만들어진 분석 도구(tool)들 중 몇개를 서술하고, 구글 내에서 이것의 사용에 대한 통계자료를 공유하고, use case들의 예를 보여주고 이때까지 배운 교훈들에 대해 논할것이다.

## 1. 도입(Introduction)
  우리는 분산 시스템의 복잡한 동작에 대해 더 많은 정보를 Google의 개발자들에게 제공하기 위해 Dapper를 만들었다. 이러한 시스템들은 특별히 흥미로운데, 작은 서버들의 큰 집합들(large collections of small servers) 은 인터넷 서비스 작업량에 있어서 특히 cost-efficient(비용 효과적) 플랫폼이기 때문이다 [4]. 이런 상황에서 시스템의 동작을 이해하려면 많은 다른 프로그램들과 기계들을 가로지르는 관련된 활동들(related activities)에 대한 관찰이 요구된다.
  web-search 예제는 이러한 시스템이 짚고넘어가야할 몇몇 문제(challenge)들을 분명히 보여준다(illustrate). front-end 서버는 각자의 index 조각 내의(within it's own piece of the index) 각각의 검색에  웹 쿼리(query)를 수백개의 많은 쿼리 서버로 보낼 것이다. 그 쿼리는 또한 process advertisemetns, check spelling, 또는 specialize된 results, including, images, videos, news 등을 찾기 위한 sub-system들로 보내질 것이다. 이 모든 서비스들로부터 받은 결과들은 선택적으로 결합되어 결과 페이지(result page)가 된다; 우리는 이 모델을 "universal search"라고 부른다 [6]. 결과적으로, 수천개의 기계들과 많든 다른 서비스들이 이 하나의 universal search 쿼리를 process 해야한다. 더욱이, 웹 검색 사용자들은 지연(delay)에 민감하고, 이는 어떤(any) sub-system의 좋지않은 성능으로도 야기될수 있다. 전체적인 지연(latency)만 보는 engineer는 아마 어떤 문제가 있다는 것을 알 것이다, 그러나 어떤 서비스가 문제가 있는지 또, 왜 그것이 좋지 않게 동작하는지에 대해서는 추측할 수 없을 것이다. 먼저, 그 engineer는 정확히 어떤 서비스가 사용되는지도 알아 수 없을 것이다; 사용자들이 볼 수 있는(user-visible) feature들을 추가하고 성능이나 보안과 같은 다른 측면들을 향상하기 위해서, 새로운 서비스들과 부품(piece)들이 매주마다 추가되고 변경될 것이다, 두번째로, 그 engineer은 모든 각각의 서비스의 내부에 대해 전문가가 아닐 것이다; 각각은 서로 다른 팀에 의해서 만들어지고 유지보수 될 것이다. 셋째로, 서비스들과 기계들은 많은 다른 client들에 의해서 동시에 공유될 것이다, 따라서 성능 결함(performance artifact; 성능적 결과, 여기서는 성능에 있어서의 문제)은 다른 어플리케이션의 동작때문에 일어나는 것일 수 있다. 예를 들어, front-ends가 다른 많은 request type들을 처리하고 있거나 Bigtable [8]과 같은 저장 시스템(storage system)은 많은 어플리케이션들과 공유될 때 가장 효율적이다.
  위에서 서술했던 시나리오는 Dapper의 두 가지 기본 요건(fundamental requirements)이 생기게 했다; ubiquitous deployment(편재형 배치) 과 continuous monitoring(지속적인 모니터링). Ubiquity(편재)는, 만약 시스템의 아주 조그만 부분이라도 모니터링되지 않으면 tracing infrastructure의 유용성이 심각하게 영향을 받을 수 있기 때문에 중요하다. 게다가, 모니터링은 언제가 켜져 있어야 한다. 왜냐하면 일반적이지 않은 케이스(case) 또는 주목할 만한(noteworthy) 시스템 동작은 다시 재현하기가 어렵거나 불가능하기 때문이다. 이러한 요구사항들로 부터 세 가지 구체적인 design goals가 생겼다.

-  Low overhead(적은 오버헤드): tracing system(추적 시스템)은 동작하고 있는 서비스에 무시해도 될 정도의 성능적 영향만을 미쳐야 한다. 어떤 고도로 최적화된 서비스에서는 작은 모니터링 오버헤드들 조차도 쉽게 눈에 띄게 되고 deployment team들이 tracing system을 끄게 만들지도 모른다.

- Application-Level transparency(어플리케이션 레벨에서의 투명성): 프로그래머들은 tracing system에 대해서 인지할 필요가 없다.
